function PreprocessFourRuns(subj,C)

    matlabbatch = Batch_pp(subj,C);
    spm_jobman('initcfg')
    spm('defaults', 'FMRI');
    spm_jobman('serial', matlabbatch);
end

function [matlabbatch]=Batch_pp(subj,C)

dir_mri = C.dir.dat_mri;
spm_funcFold = C.spm.funcFold;
spm_funcFile = C.spm.funcFile;


matlabbatch{1}.spm.util.exp_frames.files = {fullfile(dir_mri,subj,[spm_funcFold,'1'],spm_funcFile)};
matlabbatch{1}.spm.util.exp_frames.frames = Inf;
matlabbatch{2}.spm.util.exp_frames.files = {fullfile(dir_mri,subj,[spm_funcFold,'2'],spm_funcFile)};
matlabbatch{2}.spm.util.exp_frames.frames = Inf;
matlabbatch{3}.spm.util.exp_frames.files = {fullfile(dir_mri,subj,[spm_funcFold,'3'],spm_funcFile)};
matlabbatch{3}.spm.util.exp_frames.frames = Inf;
matlabbatch{4}.spm.util.exp_frames.files = {fullfile(dir_mri,subj,[spm_funcFold,'4'],spm_funcFile)};
matlabbatch{4}.spm.util.exp_frames.frames = Inf;
matlabbatch{5}.spm.temporal.st.scans{1}(1) = cfg_dep;
matlabbatch{5}.spm.temporal.st.scans{1}(1).tname = 'Session';
matlabbatch{5}.spm.temporal.st.scans{1}(1).tgt_spec{1}(1).name = 'filter';
matlabbatch{5}.spm.temporal.st.scans{1}(1).tgt_spec{1}(1).value = 'image';
matlabbatch{5}.spm.temporal.st.scans{1}(1).tgt_spec{1}(2).name = 'strtype';
matlabbatch{5}.spm.temporal.st.scans{1}(1).tgt_spec{1}(2).value = 'e';
matlabbatch{5}.spm.temporal.st.scans{1}(1).sname = 'Expand image frames: Expanded filename list.';
matlabbatch{5}.spm.temporal.st.scans{1}(1).src_exbranch = substruct('.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1});
matlabbatch{5}.spm.temporal.st.scans{1}(1).src_output = substruct('.','files');
matlabbatch{5}.spm.temporal.st.scans{2}(1) = cfg_dep;
matlabbatch{5}.spm.temporal.st.scans{2}(1).tname = 'Session';
matlabbatch{5}.spm.temporal.st.scans{2}(1).tgt_spec{1}(1).name = 'filter';
matlabbatch{5}.spm.temporal.st.scans{2}(1).tgt_spec{1}(1).value = 'image';
matlabbatch{5}.spm.temporal.st.scans{2}(1).tgt_spec{1}(2).name = 'strtype';
matlabbatch{5}.spm.temporal.st.scans{2}(1).tgt_spec{1}(2).value = 'e';
matlabbatch{5}.spm.temporal.st.scans{2}(1).sname = 'Expand image frames: Expanded filename list.';
matlabbatch{5}.spm.temporal.st.scans{2}(1).src_exbranch = substruct('.','val', '{}',{2}, '.','val', '{}',{1}, '.','val', '{}',{1});
matlabbatch{5}.spm.temporal.st.scans{2}(1).src_output = substruct('.','files');
matlabbatch{5}.spm.temporal.st.scans{3}(1) = cfg_dep;
matlabbatch{5}.spm.temporal.st.scans{3}(1).tname = 'Session';
matlabbatch{5}.spm.temporal.st.scans{3}(1).tgt_spec{1}(1).name = 'filter';
matlabbatch{5}.spm.temporal.st.scans{3}(1).tgt_spec{1}(1).value = 'image';
matlabbatch{5}.spm.temporal.st.scans{3}(1).tgt_spec{1}(2).name = 'strtype';
matlabbatch{5}.spm.temporal.st.scans{3}(1).tgt_spec{1}(2).value = 'e';
matlabbatch{5}.spm.temporal.st.scans{3}(1).sname = 'Expand image frames: Expanded filename list.';
matlabbatch{5}.spm.temporal.st.scans{3}(1).src_exbranch = substruct('.','val', '{}',{3}, '.','val', '{}',{1}, '.','val', '{}',{1});
matlabbatch{5}.spm.temporal.st.scans{3}(1).src_output = substruct('.','files');
matlabbatch{5}.spm.temporal.st.scans{4}(1) = cfg_dep;
matlabbatch{5}.spm.temporal.st.scans{4}(1).tname = 'Session';
matlabbatch{5}.spm.temporal.st.scans{4}(1).tgt_spec{1}(1).name = 'filter';
matlabbatch{5}.spm.temporal.st.scans{4}(1).tgt_spec{1}(1).value = 'image';
matlabbatch{5}.spm.temporal.st.scans{4}(1).tgt_spec{1}(2).name = 'strtype';
matlabbatch{5}.spm.temporal.st.scans{4}(1).tgt_spec{1}(2).value = 'e';
matlabbatch{5}.spm.temporal.st.scans{4}(1).sname = 'Expand image frames: Expanded filename list.';
matlabbatch{5}.spm.temporal.st.scans{4}(1).src_exbranch = substruct('.','val', '{}',{4}, '.','val', '{}',{1}, '.','val', '{}',{1});
matlabbatch{5}.spm.temporal.st.scans{4}(1).src_output = substruct('.','files');
matlabbatch{5}.spm.temporal.st.nslices = 36;
matlabbatch{5}.spm.temporal.st.tr = 3;
matlabbatch{5}.spm.temporal.st.ta = 2.91666666666667;
matlabbatch{5}.spm.temporal.st.so = [2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 1 3 5 7 9 11 13 15 17 19 21 23 25 27 29 31 33 35];
matlabbatch{5}.spm.temporal.st.refslice = 36;
matlabbatch{5}.spm.temporal.st.prefix = 'a';
matlabbatch{6}.spm.spatial.realign.estwrite.data{1}(1) = cfg_dep;
matlabbatch{6}.spm.spatial.realign.estwrite.data{1}(1).tname = 'Session';
matlabbatch{6}.spm.spatial.realign.estwrite.data{1}(1).tgt_spec{1}(1).name = 'filter';
matlabbatch{6}.spm.spatial.realign.estwrite.data{1}(1).tgt_spec{1}(1).value = 'image';
matlabbatch{6}.spm.spatial.realign.estwrite.data{1}(1).tgt_spec{1}(2).name = 'strtype';
matlabbatch{6}.spm.spatial.realign.estwrite.data{1}(1).tgt_spec{1}(2).value = 'e';
matlabbatch{6}.spm.spatial.realign.estwrite.data{1}(1).sname = 'Slice Timing: Slice Timing Corr. Images (Sess 1)';
matlabbatch{6}.spm.spatial.realign.estwrite.data{1}(1).src_exbranch = substruct('.','val', '{}',{5}, '.','val', '{}',{1}, '.','val', '{}',{1});
matlabbatch{6}.spm.spatial.realign.estwrite.data{1}(1).src_output = substruct('()',{1}, '.','files');
matlabbatch{6}.spm.spatial.realign.estwrite.data{2}(1) = cfg_dep;
matlabbatch{6}.spm.spatial.realign.estwrite.data{2}(1).tname = 'Session';
matlabbatch{6}.spm.spatial.realign.estwrite.data{2}(1).tgt_spec{1}(1).name = 'filter';
matlabbatch{6}.spm.spatial.realign.estwrite.data{2}(1).tgt_spec{1}(1).value = 'image';
matlabbatch{6}.spm.spatial.realign.estwrite.data{2}(1).tgt_spec{1}(2).name = 'strtype';
matlabbatch{6}.spm.spatial.realign.estwrite.data{2}(1).tgt_spec{1}(2).value = 'e';
matlabbatch{6}.spm.spatial.realign.estwrite.data{2}(1).sname = 'Slice Timing: Slice Timing Corr. Images (Sess 2)';
matlabbatch{6}.spm.spatial.realign.estwrite.data{2}(1).src_exbranch = substruct('.','val', '{}',{5}, '.','val', '{}',{1}, '.','val', '{}',{1});
matlabbatch{6}.spm.spatial.realign.estwrite.data{2}(1).src_output = substruct('()',{2}, '.','files');
matlabbatch{6}.spm.spatial.realign.estwrite.data{3}(1) = cfg_dep;
matlabbatch{6}.spm.spatial.realign.estwrite.data{3}(1).tname = 'Session';
matlabbatch{6}.spm.spatial.realign.estwrite.data{3}(1).tgt_spec{1}(1).name = 'filter';
matlabbatch{6}.spm.spatial.realign.estwrite.data{3}(1).tgt_spec{1}(1).value = 'image';
matlabbatch{6}.spm.spatial.realign.estwrite.data{3}(1).tgt_spec{1}(2).name = 'strtype';
matlabbatch{6}.spm.spatial.realign.estwrite.data{3}(1).tgt_spec{1}(2).value = 'e';
matlabbatch{6}.spm.spatial.realign.estwrite.data{3}(1).sname = 'Slice Timing: Slice Timing Corr. Images (Sess 3)';
matlabbatch{6}.spm.spatial.realign.estwrite.data{3}(1).src_exbranch = substruct('.','val', '{}',{5}, '.','val', '{}',{1}, '.','val', '{}',{1});
matlabbatch{6}.spm.spatial.realign.estwrite.data{3}(1).src_output = substruct('()',{3}, '.','files');
matlabbatch{6}.spm.spatial.realign.estwrite.data{4}(1) = cfg_dep;
matlabbatch{6}.spm.spatial.realign.estwrite.data{4}(1).tname = 'Session';
matlabbatch{6}.spm.spatial.realign.estwrite.data{4}(1).tgt_spec{1}(1).name = 'filter';
matlabbatch{6}.spm.spatial.realign.estwrite.data{4}(1).tgt_spec{1}(1).value = 'image';
matlabbatch{6}.spm.spatial.realign.estwrite.data{4}(1).tgt_spec{1}(2).name = 'strtype';
matlabbatch{6}.spm.spatial.realign.estwrite.data{4}(1).tgt_spec{1}(2).value = 'e';
matlabbatch{6}.spm.spatial.realign.estwrite.data{4}(1).sname = 'Slice Timing: Slice Timing Corr. Images (Sess 4)';
matlabbatch{6}.spm.spatial.realign.estwrite.data{4}(1).src_exbranch = substruct('.','val', '{}',{5}, '.','val', '{}',{1}, '.','val', '{}',{1});
matlabbatch{6}.spm.spatial.realign.estwrite.data{4}(1).src_output = substruct('()',{4}, '.','files');
matlabbatch{6}.spm.spatial.realign.estwrite.eoptions.quality = 0.9;
matlabbatch{6}.spm.spatial.realign.estwrite.eoptions.sep = 4;
matlabbatch{6}.spm.spatial.realign.estwrite.eoptions.fwhm = 5;
matlabbatch{6}.spm.spatial.realign.estwrite.eoptions.rtm = 1;
matlabbatch{6}.spm.spatial.realign.estwrite.eoptions.interp = 2;
matlabbatch{6}.spm.spatial.realign.estwrite.eoptions.wrap = [0 0 0];
matlabbatch{6}.spm.spatial.realign.estwrite.eoptions.weight = '';
matlabbatch{6}.spm.spatial.realign.estwrite.roptions.which = [2 1];
matlabbatch{6}.spm.spatial.realign.estwrite.roptions.interp =   4;
matlabbatch{6}.spm.spatial.realign.estwrite.roptions.wrap = [0 0 0];
matlabbatch{6}.spm.spatial.realign.estwrite.roptions.mask = 1;
matlabbatch{6}.spm.spatial.realign.estwrite.roptions.prefix = 'r';
end
