function scores = rsj_rsa_getbetas(subj,C)

inDir =  fullfile(C.dir.dir_rs,C.spm.spm_modelName,...
    ['hpf',num2str(C.spm.spm_hpf)],C.spm.spm_mask,...
    C.spm.spm_smooth,C.masks.maskType,'betas',...
    C.rs.rs_feature_mask,'scores',...
    ['OLSv_method_',C.ol.ol_v_method],['OLSv_',C.ol.ol_v]);

fName =  [subj, '_scores'];
scores = load(fullfile(inDir,fName));

